### ISSUE TITLE
How to make brush from texture?

### ISSUE THREAD

**Issue by rashidabbas** [Asana/Drawsana#12]
Dear Sir I have used your framework its working is awesome but I need to create brush from texture . kindly help me how to create brush tool from image texture like painting brushes.

just like this demo.
https://github.com/Harley-xk/MaLiang

thanks in advance.

**Comment by stevelandeyasana** [comment]
You will have to do your own Core Graphics research and modify the Pen tool.

I'm closing this because ultimately it's a help-style question and not an issue with the library, but do feel free to submit a pull request if you improve it!
