### ISSUE TITLE
Eraser tool doesn't work if drawing was loaded from JSON

### ISSUE THREAD

**Issue by StasMalinovsky** [Asana/Drawsana#13]
Hello! Eraser tool doesn't work on drawing view if it's `drawing` property was set.
`do {
            self.drawingView.drawing = try JSONDecoder().decode(Drawing.self, from: data)
        } catch let error {
            print(error)
        }`
Any suggestions?
Thank you!

**Comment by stevelandeyasana** [comment]
Thanks for the heads up. I'll take a look in the next maintenance pass.

**Comment by stevelandeyasana** [comment]
I can't reproduce this issue. I tried adding a button to the demo view controller that saves and loads the drawing. Then I briefly scribbled with the pen and eraser. The reload button worked for me.

I'll reopen if you can provide the specific error message you're getting.

**Comment by stevelandeyasana** [comment]
I think this is a duplicate of #27, and I have a fix in #31.
