### ISSUE TITLE
Rotating device does not adjust drawing for updated aspect ratios

### ISSUE THREAD

**Issue by jeffstay** [Asana/Drawsana#16]
Using the sample demo project, if you draw in portrait, then rotate to landscape and start drawing again, the drawing shifts on the screen.

**Comment by jeffstay** [comment]
figured how to handle this.  Wrapped the DrawingView in a view that lives in a UIScrollView.  This allows for transforms on the base image and the drawing

**Comment by dneykov** [comment]
Hi @jeffstay,

can you give rough example of your solution because I have same issue. Thanks
