### ISSUE TITLE
Canvas view is not recognising touches after coming from background (device: iPad)

### ISSUE THREAD

**Issue by Kiran-appitventures** [Asana/Drawsana#24]
When the app is sent to background via sliding from the bottom and then opening the app, the touches are not recognizing again and getting below crash.

`assert(false, "State not handled")` (DrawsanaView.swift -> 302 line)

**Comment by stevelandeyasana** [comment]
Thanks for the report. If you disable asserts it probably won't crash in release builds. :-) I'll look into it when I get a chance.

**Comment by stevelandeyasana** [comment]
@Kiran-appventures If you disable the assert, does the app keep working normally? It should. So this won't affect production builds.

Still worth a look, of course!

**Comment by stevelandeyasana** [comment]
Would you mind trying this branch to see if it fixes the issue? https://github.com/Asana/Drawsana/pull/32

**Comment by dneykov** [comment]
Hello, 

I have same problem

**Comment by stevelandeyasana** [comment]
OK, did you also try my suggestion? Did it work?

This PR might fix it but I can't merge it until someone confirms: https://github.com/Asana/Drawsana/pull/32

**Comment by dneykov** [comment]
@stevelandeyasana I just test with the branch with the fix but still crashes but on different line

`Assertion failed: State not handled: file /Users/dneykov/Developer/iOS Apps/Schouw/Pods/Drawsana/Drawsana/DrawsanaView.swift, line 301
2019-07-29 10:24:07.900861+0300 Schouw[5333:1463336] Assertion failed: State not handled: file /Users/dneykov/Developer/iOS Apps/Schouw/Pods/Drawsana/Drawsana/DrawsanaView.swift, line 301`

**Comment by Kiran-appitventures** [comment]
As drawing is not happening when app resigns active screen.. temporarily done workaround.

In Drawsana:

panGR as global variable

public func resetPanGR() {
        DispatchQueue.main.async {
            self.panGR.state = .ended
            self.panGR.reset()
        }
   } 


In my DrawingVC calling this:
@objc private func handleDidBecomeActiveNotification() {
         drawingView.resetPanGR()
  }
