### ISSUE TITLE
shapes not adding in the decoded drawing operation stack

### ISSUE THREAD

**Issue by SanjeevSundaravarathan** [Asana/Drawsana#35]
Hi, 

I am decoding drawing from data and adding them on the drawing view. When I added new pen stokes on the same same drawing view, those stokes are not added in the operation stack for me save decoded drawing + new pen stokes. If I saved, I am getting on old decoded layers only , new stokes are adding to the data.

**Comment by stevelandeyasana** [comment]
Thanks for the report. This area of Drawsana was not well tested at release time, and it's unlikely I'll be able to investigate soon.

I suspect it won't be difficult to fix if one were to dig into the project and read the code paths. This is a pretty small project (<3000 lines).

**Comment by stevelandeyasana** [comment]
I think this is a duplicate of #37.
