### ISSUE TITLE
[question] Is there a reason why the id of a Shape is a get-only-property?

### ISSUE THREAD

**Issue by sebhell** [Asana/Drawsana#41]
When creating Shapes from a network-based update you have to downcast the shape to a subclass like LineShape or RectShape, if you want to set the id. Which leads to duplicate code.

So is there a reason why the id property of the shape protocol couldn't be settable?

``` 
public protocol Shape: AnyObject, Codable  #{
  /// Globally unique identifier for this shape. Meant to be used for equality
  /// checks, especially for network-based updates.
  var id: String { get }
  ...

**Comment by stevelandeyasana** [comment]
No real reason, we just didn't anticipate this use case. PRs will be accepted. :-)
