### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by ZuYuanZhou** [Asana/Drawsana#42]
Nice project, hope can add swift package manager support!

**Comment by ZuYuanZhou** [comment]
Some files missing explicit imports when using SPM.

E.g. DrawingOperationStack.swift missing 'import Foundation'

**Comment by ZuYuanZhou** [comment]
I have create a PR to fix this issue, please have a check. @stevelandeyasana

**Comment by stevelandeyasana** [comment]
Thanks! It's possible to have GitHub PRs automatically close issues by referencing them in the description. So you could say in your PR description, "Fixes #42", and it would link to this issue and close it after the PR is merged.
