### ISSUE TITLE
Hope to increase the function of drawing dashed lines

### ISSUE THREAD

**Issue by kenpig** [Asana/Drawsana#52]
Nice project, hope to increase the function of drawing dashed lines. 

Thank you very much

**Comment by stevelandeyasana** [comment]
Increase in what way? It's already possible to set whatever pattern you want. Set `LineShape.dashPhase` and `LineShape.dashLength`.

https://developer.apple.com/documentation/coregraphics/cgcontext/2427130-setlinedash

**Comment by kenpig** [comment]
Thank you very much for your detailed answer.
