### ISSUE TITLE
Question: ViewWillAppear vs ViewDidAppear to load drawing 

### ISSUE THREAD

**Issue by ramjyroo** [Asana/Drawsana#60]
I have stored the JSON string of the drawing and want to reload it back into DrawingView. 

```
func loadScratchText() {
        let jsonDecoder = JSONDecoder()
        let scratchText = self.viewModel.scratchText
        print("scratchText: \(scratchText)")
        guard let jsonData = scratchText.data(using: .utf8) else {
            return
        }
        guard let drawing = try? jsonDecoder.decode(Drawing.self, from: jsonData) else {
            print("Unable to load scratch json")
            return
        }
        self.drawingView.drawing = drawing
        print(drawingView.drawing.shapes)
        print("")
    }
```

If I call this function in viewWillAppear - it prints the shapes but the drawing is NOT visible. But when I use viewDidAppear - it does nicely render back the drawing.

Is this expected behavior? 

thanks
Ram

**Comment by stevelandeyasana** [comment]
You're probably seeing this because I forgot to merge #58 and do a release. :-) Would you mind trying again with the latest `master` branch?

**Comment by ramjyroo** [comment]
Sure thanks so much!

**Comment by ramjyroo** [comment]
Thanks a bunch !! It is definitely working as expected with the latest master branch.
