### ISSUE TITLE
How to make Touch Visualizer effect in DrawsanaView?

### ISSUE THREAD

**Issue by guanyu7778** [Asana/Drawsana#8]
Hi Sir, I want to add a Touch Visualizer effect in DrawsanaView like the gif below. please give me some help, Thanks

![](https://github.com/morizotter/TouchVisualizer/blob/master/misc/one.gif)

**Comment by stevelandeyasana** [comment]
I still don't really understand what you mean. Are you trying to display an icon under each finger?
